[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"


[project]
name = "wpt-manager"
version = "0.1.0"
description = "Waypoint manager and OsmAnd GPX exporter"
requires-python = ">=3.14"
dependencies = [
    "PySide6==6.11.2",
]

[project.optional-dependencies]
test = [
    "pytest==9.1.1",
]
build = [
    "PyInstaller==6.22.2",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["wpt_manager*"]
